
-- SCHEMA
-- CREATE SCHEMA IF NOT EXISTS "PUBLIC";

-- USER
-- CREATE USER IF NOT EXISTS tester PASSWORD 'tester';
-- ALTER USER tester ADMIN TRUE;
-- GRANT ALL TO tester;

ALTER TABLE member ADD COLUMN addr VARCHAR (70) NOT NULL;